"""empty message

Revision ID: 31c67232f3da
Revises: 3065cc8f47db
Create Date: 2019-10-02 00:44:18.419123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c67232f3da'
down_revision = '3065cc8f47db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'limit')
    # ### end Alembic commands ###
