"""Convert user session association to use class with extra columns for booked, paid. Add credit to User. Add cost to Session

Revision ID: caa16137aca1
Revises: 22c52fdb7e74
Create Date: 2019-10-06 01:51:37.586473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa16137aca1'
down_revision = '22c52fdb7e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    op.drop_table('users')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost_u18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credit')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('cost_u18')
        batch_op.drop_column('cost')

    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    op.drop_table('user_session')
    # ### end Alembic commands ###
